[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"